
import time
from furhat_remote_api import FurhatRemoteAPI

def run_action(ip: str):
    furhat = FurhatRemoteAPI(ip)
    furhat.set_face(mask="adult", character="Yumi")
    
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS3.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS2.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/oneRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/twoRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/threeRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/fourRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/fiveRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/sixRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/sevenRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/eightRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/nineRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/tenRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS4.wav", lipsync=True)
    time.sleep(20)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS5.wav", lipsync=True)
    time.sleep(10)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/oneRUS.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/twoRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/threeRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/fourRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/fiveRUS.wav", lipsync=True)
    time.sleep(7)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS6.wav", lipsync=True)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS7.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS8.wav", lipsync=True)
    time.sleep(12)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS9.wav", lipsync=True)
    time.sleep(35)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingRUS/CountingNumbersRUS/CountingRUS10.wav", lipsync=True)
  
