
import time
from furhat_remote_api import FurhatRemoteAPI

def run_action(ip: str):
    furhat = FurhatRemoteAPI(ip)
    furhat.set_face(mask="adult", character="Yumi")
    
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ3.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ2.wav", lipsync=True)
    time.sleep(12)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/oneKAZ.wav", lipsync=True)
    time.sleep(12)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/twoKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/threeKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/fourKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/fiveKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/sixKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/sevenKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/eightKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/nineKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/tenKAZ.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ4.wav", lipsync=True)
    time.sleep(20)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ5.wav", lipsync=True)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ6.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/oneKAZ.wav", lipsync=True)
    time.sleep(5)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/twoKAZ.wav", lipsync=True)
    time.sleep(5)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/threeKAZ.wav", lipsync=True)
    time.sleep(5)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/fourKAZ.wav", lipsync=True)
    time.sleep(5)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/fiveKAZ.wav", lipsync=True)
    time.sleep(5)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ7.wav", lipsync=True)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ8.wav", lipsync=True)
    time.sleep(13)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ9.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ10.wav", lipsync=True)
    time.sleep(10)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ11.wav", lipsync=True)
    time.sleep(20)
    furhat.say(url="file:///home/furnix/resources/Counting/CountingKAZ/CountingNumbersKAZ/CountingKAZ12.wav", lipsync=True)

