
import time
from furhat_remote_api import FurhatRemoteAPI

def run_action(ip: str):
    furhat = FurhatRemoteAPI(ip)
    furhat.set_face(mask="adult", character="Yumi")
    

    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS1_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS2_n.wav", lipsync=True)
    time.sleep(15)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS3_n.wav", lipsync=True)
    time.sleep(5)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS4_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS5_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS6_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS7_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS8_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS9_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS10_n.wav", lipsync=True)
    time.sleep(1)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS11_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS4_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS5_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS6_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS7_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS8_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS9_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS10_n.wav", lipsync=True)
    time.sleep(3)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS12_n.wav", lipsync=True)
    time.sleep(20)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/KozheRUS/KozheRUS13_n.wav", lipsync=True)
    time.sleep(2)
    furhat.say(url="file:///home/furnix/resources/HolidaysRUS/BirthdayRUS/BirthdayRUS11_n.wav", lipsync=True)

    
